mysql:
  datasource:
    #读库数目
    num: 1
    type-aliases-package: com.example.dxfl.dao
    mapper-locations: classpath:/mapper/*.xml
    config-location: classpath:/mybatis-config.xml
    write:
      url: jdbc:mysql://127.0.0.1:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: test_db
      password: test_db
      driver-class-name: com.mysql.jdbc.Driver
    read:
      url: jdbc:mysql://127.0.0.1:3307/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: test_db
      password: test_db
      driver-class-name: com.mysql.jdbc.Driver